@startuml
'https://plantuml.com/class-diagram

package "Job Opening Aggregate"{

    class "«entity»\nRecruitmentProcess" as RecruitmentProcess{
        HasInterviewPhase
    }

     class "«entity»\nPhase" as Phase{
        phaseName
        startDate
        endDate
     }

    class "«value object»\nPhaseNames" as PhaseNames{

    }


 class "«entity»\nScreeningPhase" as ScreeningPhase{

     }

    class "«entity»\nResultPhase" as ResultPhase{
    }

    class "«entity»\nAnalysisPhase" as AnalysisPhase{

    }

    class "«root»\n«entity» \nJobOpening" as JobOpening{


    }

    class "«value object»\nJogOpeningStatus" as JogOpeningStatus {
    }

     class "«value object»\nContractType" as ContractType{
     }

    class "«value object»\nMode" as Mode{

    }

    class "«value object»\nJobFunction" as JobFunction{

    }

    class "«value object»\n NumberOfVacancies" as  NumberOfVacancies{

    }

    class "«value object»\nDescription" as Description{

    }


    class "«value object»\nAddress" as Address1{
        Street
        City
        State
        Country
        Zipcode
    }

    class "«value object»\n«identifier»\nJobReference" as JobReference{
    }

    class  "«entity»\nInterviewPhase" as InterviewPhase{

    }

}

package "Notification Aggregate"{
    class "«entity»\nNotification" as Notification{
    }
}


Mode "1" <-- "1"JobOpening : includes
JobFunction "1" <-- "1"JobOpening : includes
NumberOfVacancies "1" <-- "1"JobOpening : includes
Description "1" <-- "1"JobOpening : includes
Address1"1" <-- "1"JobOpening : includes
ContractType "1" <--"1" JobOpening : includes



JobOpening "1"-->"1" JobReference : identified by

JobOpening "1"-->"1" JogOpeningStatus : includes
RecruitmentProcess "1" *--"4..5" Phase :part of
RecruitmentProcess "1" -> "1" PhaseNames : includes
JobOpening "1" --> "1"RecruitmentProcess :includes


ScreeningPhase --|> Phase
ResultPhase --|> Phase
InterviewPhase --|> Phase
AnalysisPhase --|> Phase

ScreeningPhase --> Notification : sends
RecruitmentProcess --> Notification : sends




@enduml