@startuml
'https://plantuml.com/class-diagram



package "JobApplication Aggregate"{
    class "«root»\n«entity»\nJobApplication" as JobApplication{

    }
    class "«value object»\nStatus" as Status{
    }

     class "«value object»\n«identifier»\nId" as ID{
     }

    class "«value object»\n«calculated»\nGrade" as Grade{}


    class "«value object»\nApplicationFile" as ApplicationFile{
    relativeFilePath
    fileContent


    }

    class "«value object»\nType" as Type{
    }
}

package "Candidate Aggregate"{
    class "«root»\n«entity»\nCandidate" as Candidate{

    }

    class "«value object»\nName" as Name2 {
        firstName
        lastName
    }

    class "«value object»\nPhoneNumber" as PhoneNumber{
    }

     class "«value object»\n«identifier»\nE-Mail" as EMail2{
     }

}

Candidate "1" <-- "1" JobApplication :refers to
Candidate --> Name2 : has
Candidate "1"-->"1" EMail2 :identified by
PhoneNumber "1"<-"1" Candidate :has


JobApplication"1"-->"1" ID : identified by
JobApplication "1" --> "1..*" ApplicationFile
ApplicationFile "1" --> "1" Type
JobApplication --> "0..1" Grade : includes
JobApplication "1"-->"1" Status : has


@enduml