@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

title "US1017 - Upload a text file with the candidate responses for an interview" Sequence Diagram
'hide footbox
actor "Operator" as CM
participant ":ImportInterviewFileUI" as UI <<presentation>>
control ":ImportInterviewFileController" as CTRL <<application>>
participant ":JobOpeningRepository" as OR <<repository>>
participant ":JobApplicationRepository" as AR <<repository>>
participant ":JobApplication" as JA
participant ":JobOpening" as JO
participant ":ImportFolderReader" as File
participant "jarClass :jarClass" as JAR <<interviewInterface>>


activate CM

    CM -> UI : Asks to select a Job Opening

    activate UI

        UI -> CTRL** : create


        UI -> CTRL : getJobOpenings()
        activate CTRL
        CTRL->OR : getJobOpenings()
           activate OR
           OR --> CTRL : openingList()
           deactivate OR
           CTRL --> UI : openingList()
           deactivate CTRL




    UI -> CM: Show the list of all job openings and request the selection of one

    deactivate UI

    CM -> UI : Selects a jobOpening
    activate UI
        UI -> CTRL : getJobApplicationsByOpening(jobOpening)
        activate CTRL
        CTRL->AR : findByJobOpening(jobOpening)
           activate AR
           AR --> CTRL : applicationList
           deactivate AR
           CTRL --> UI : applicationList
           deactivate CTRL
        UI --> CM : Show the list of all job applications made to the selected job opening and request the selection of one

    deactivate UI

    CM -> UI : Selects a jobApplication
    activate UI
    UI -> File : getFilesFromImportFolder()
    activate File
           File --> UI : fileList()
           deactivate File
        UI --> CM : Show the list of files and request the selection of one

    deactivate UI

    CM -> UI : Selects a file
    activate UI
    UI -> CTRL : validateAndAddFile(file, jobApplication, jobOpening)
    activate CTRL
    CTRL -> JO : getInterviewPlugin()
    activate JO
    JO --> CTRL: interviewPlugin
    deactivate JO
    CTRL -> JAR** : create
    CTRL -> JAR: antlr(file)
    activate JAR
    JAR --> CTRL : valid
    deactivate JAR
    CTRL -> JA : addFile(file)
    activate JA
    JA --> CTRL : success
    deactivate JA
    CTRL --> UI : success
    deactivate CTRL
    UI --> CM : success
    deactivate UI



    deactivate UI
deactivate CM

@enduml