@startuml

title "US 1007  As Customer Manager, I want to setup the phases of the process for a job opening."

class "SetupPhasesJobOpeningUI" as UI{
    -selectHaveInterview() : boolean
    -selectDates(hasInterview) : List<Phase>
    -checkTimePeriodBetweenPhase(phases, timePeriodApplication) : boolean
    -setTimePeriod(message) : List<Calendar>
    -getDateFromUser(prompt, scanner) : Calendar
    -selectJobOpening(jobOpenings) : JobOpening

}

class PersistenceContext{
    repositories()
}

class "SetupPhasesJobOpeningController" as Controller{
    +setUpPhasesJobOpening(jobOpening, dates, hasInterview) : JobOpening
    +jobOpeningByCustomerManager() : List<JobOpening>
}

interface "RepositoryFactory" as Factory{
    jobOpenings()
    jobOpenings(TransactionalContext tx)
}


interface JobOpeningRepository{
    jobOpenings()
    findAll()

}

class JobOpening {
 -jobReference : JobReference
 -numberOfVacancies : NumberOfVacancies
 -jobFunction : JobFunction
 -contractType : ContractType
 -mode : Mode
 -address : Address
 -companyName : Customer
 -description :Description
 -registrationDate : Calendar
 -recruitmentProcess : RecruitmentProcess
 -requirementsPlugin : Plugin
 -interviewPlugin : Plugin


 +setRecruitmentProcess(recruitmentProcess)

 }

 class JobReference{
     - jobReference : Integer
 }

 class JobFunction{
     - jobDescription : String
 }

 class NumberOfVacancies{
     - number : Integer
 }

 class ContractType{
     - contractType : String
 }


 class Mode{
  -modeDescription : String
 }

 class Description{
     - description : String
 }

 class Plugin{
    - pluginID : PluginIdentifier
    - pluginType : PluginType
    - description : Description
    - pluginMainClassName : PluginMainClassName
    - jarFileName : JarFileName

 }

 class Customer{
     - systemUser : SystemUser
     - code : Code
     - address : Address
     - customerManager : SystemUser
 }

 class RecruitmentProcess{
     - hasInterview : boolean
     - phases : List<Phase>
     +RecruitmentProcess(hasInterview, phases)
 }

abstract Phase {
    -TimePeriod timePeriod
    +Phase (beginDate, endDate)
}

class TimePeriod {
    - Calendar beginDate
    - Calendar endDate
    +TimePeriod(beginDate, endDate)
}

class ApplicationPhase {
    +ApplicationPhase(beginDate, endDate)
}

class AnalysisPhase {
    +AnalysisPhase(beginDate, endDate)
}

class InterviewPhase {
    +InterviewPhase(beginDate, endDate)
}

class ResultPhase {
    +ResultPhase(beginDate, endDate)
}

class ScreeningPhase {
    +ScreeningPhase(beginDate, endDate)
}


 class Address{
     - street : String
     - city : String
     - state : String
     - country : String
     - zipcode : String

     - validateZipcode(zipcode) : boolean
 }

UI ..> Controller

Controller ..> PersistenceContext
Controller ..> JobOpeningRepository

PersistenceContext->Factory
Factory ..> JobOpeningRepository

JobOpeningRepository --> "*" JobOpening :stores


JobOpening --> Address
JobOpening --> Mode
JobOpening --> Customer
JobOpening --> ContractType
JobOpening --> JobFunction
JobOpening --> JobReference
JobOpening --> Description
JobOpening --> NumberOfVacancies
JobOpening --> RecruitmentProcess
JobOpening --> "0..2" Plugin

RecruitmentProcess *-- Phase
Phase --> TimePeriod
AnalysisPhase --|> Phase
ResultPhase --|> Phase
ScreeningPhase --|> Phase
ApplicationPhase --|> Phase
InterviewPhase --|> Phase




@enduml