@startuml
'https://plantuml.com/class-diagram

package "Candidate Aggregate"{
    class "«root»\n«entity»\nCandidate" as Candidate{

    }
    note as EmailCandidate
                      Identifier
                     end note


    class "Name" as Name {
        firstName
        lastName
    }

    class "«value object»\nPhoneNumber" as PhoneNumber{
    phoneNumber
    }

     class "«value object»\nE-Mail" as EMail{
     email
     }

}

class UserDomain{
}
EmailCandidate.EMail
Candidate "1"-->"1" EMail :identified by
PhoneNumber "1"<-"1" Candidate :has
Candidate"1" --> "1" Name : has

Candidate "1"..>"1" UserDomain

@enduml